services:
  # subscriber:
  #   build: ./test
  #   working_dir: /code
  #   volumes:
  #     - ./test:/code
  #   depends_on:
  #     - broker

  # broker:
  #   image: vernemq/vernemq
  #   restart: unless-stopped
  #   ports: 
  #     - 1883:1883
  #   environment:
  #     DOCKER_VERNEMQ_ACCEPT_EULA: "yes"
  #     DOCKER_VERNEMQ_ALLOW_ANONYMOUS: "off"
  #     DOCKER_VERNEMQ_PLUGINS__VMQ_PASSWD: "off"
  #     DOCKER_VERNEMQ_PLUGINS__VMQ_ACL: "off"
  #     DOCKER_VERNEMQ_PLUGINS__VMQ_DIVERSITY: "on"
  #     DOCKER_VERNEMQ_VMQ_DIVERSITY__HTTP_AUTH__file: "/auth_http.lua"
  #     HTTP_AUTH: auth
  #   volumes:
  #     - ./vernemq/auth_http.lua:/auth_http.lua
  
  # auth:
  #   build: ./jwt
  #   restart: unless-stopped
  #   volumes:
  #     - ./jwt:/code
  #   ports:
  #     - 3000:3000 

  # transport:
  #   container_name: transport
  #   image: rabbitmq:3.8.14-management
  #   restart: unless-stopped
  #   hostname: rabbit

  backend:
    build: ./backend
    # restart: always
    volumes:
      - ./backend:/code
    ports:
      - 5000:5000
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: bpiot
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      PORT: 5000
    depends_on:
      # - auth
      - db

  db:
    image: "timescale/timescaledb:2.1.0-pg12"
    ports:
      - 5432:5432
    environment:
      # POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    volumes:
      - ./db/data:/var/lib/postgresql/data

  # tsdb:
  #   image: "influxdb:2.0-alpine"
  #   ports:
  #     - 8086:8086
  #   environment:

  #   volumes: 
  #     - ./db/ts:/var/lib/influxdb
